In [14]:
import pandas as pd 
import numpy as np

In [15]:
df = pd.read_csv('..\data\cleaned\employment_cleaned.csv')

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_10928\3081294922.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df = pd.read_csv('..\data\cleaned\employment_cleaned.csv')

In [16]:
df.head()

,id,AgeAbove35,Accessibility,EdLevel,Employment,Gender,MentalHealth,MainBranch,YearsCode,YearsCodePro,Country,PreviousSalary,HaveWorkedWith,ComputerSkills,Employed
0,0,0,False,Master,1,Man,False,Dev,7,4,Sweden,51552.0,"['C++', 'Python', 'Git', 'PostgreSQL']",4,0
1,1,0,False,Undergraduate,1,Man,False,Dev,12,5,Spain,46482.0,"['Bash/Shell', 'HTML/CSS', 'JavaScript', 'Node...",12,1
2,2,0,False,Master,1,Man,False,Dev,15,6,Germany,77290.0,"['C', 'C++', 'Java', 'Perl', 'Ruby', 'Git', 'R...",7,0
3,3,0,False,Undergraduate,1,Man,False,Dev,9,6,Canada,46135.0,"['Bash/Shell', 'HTML/CSS', 'JavaScript', 'PHP'...",13,0
4,4,1,False,PhD,0,Man,False,NotDev,40,30,Singapore,160932.0,"['C++', 'Python']",2,0

In [17]:
df1 = pd.read_csv('..\data\cleaned\skills.csv')
df1.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_10928\1065859100.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df1 = pd.read_csv('..\data\cleaned\skills.csv')

   id HaveWorkedWith
0   0            C++
1   0         Python
2   0            Git
3   0     PostgreSQL
4   1     Bash/Shell

In [19]:
top_countries = df['Country'].value_counts().head(10).index
df['Country_grouped'] = df['Country'].where(df['Country'].isin(top_countries), 'Other')
df['Country_grouped'].value_counts()

Country_grouped
Other                                                   29875
United States of America                                14696
Germany                                                  5395
India                                                    5360
United Kingdom of Great Britain and Northern Ireland     4688
Canada                                                   2779
France                                                   2650
Brazil                                                   2624
Poland                                                   1922
Netherlands                                              1761
Spain                                                    1712
Name: count, dtype: int64

Countries have 172 unique values , instead we just use the top 10 countries in our analysis and the rest are put in 'others'

In [25]:
df['Skills_dist'] = pd.qcut(df['ComputerSkills'], q=3, labels=['Low','Medium','High'])

print(df['Skills_dist'].value_counts().sort_values(ascending=False))

Skills_dist
Low       27422
High      24169
Medium    21871
Name: count, dtype: int64

to make easy comparisons using skills

In [26]:
df['Age_Gender'] = df['AgeAbove35'].astype(str) + '_' + df['Gender'].astype(str)
df['Age_Gender']

0              0_Man
1              0_Man
2              0_Man
3              0_Man
4              1_Man
            ...
73457          0_Man
73458          1_Man
73459          0_Man
73460          0_Man
73461    0_NonBinary
Name: Age_Gender, Length: 73462, dtype: str

to make comparisons using the 2 features in one column

In [28]:
df['has_advanced_degree'] = df['EdLevel'].isin(['Master', 'PhD']).astype(int)
df['skills_x_advanced_degree'] = df['ComputerSkills'] * df['has_advanced_degree']
df['skills_x_advanced_degree']

0        4
1        0
2        7
3        0
4        2
        ..
73457    0
73458    0
73459    0
73460    0
73461    2
Name: skills_x_advanced_degree, Length: 73462, dtype: int64

as we found skills matter more than the degree itself

In [29]:
df['salary_per_year_exp'] = df['PreviousSalary'] / (df['YearsCodePro'] + 1)
df['salary_per_year_exp']

0        10310.400000
1         7747.000000
2        11041.428571
3         6590.714286
4         5191.354839
             ...
73457    13686.000000
73458     6764.705882
73459    14430.000000
73460    35000.000000
73461    18846.000000
Name: salary_per_year_exp, Length: 73462, dtype: float64

to show how efficient the experience converts to pay